[package]
name = "rusty-reading"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.5.1"
gen-fixture = { path = "./gen-fixture" }

[[bench]]
name = "main"
harness = false
